<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * B3 — "Registrar en el historial el envio del link de pago y el pago recibido".
 *
 * Turns reservation_email_history into a lightweight reservation timeline
 * (no new table): system emails (payment link, reservation received, week
 * reminder, abandoned cart follow-up) and non-email events (payment received)
 * are stored side by side.
 *
 *  - template_id becomes NULLABLE: automatic sends render by slug and the
 *    "payment received" row is not tied to any template.
 *  - The FK on template_id is dropped and re-added with ON DELETE SET NULL
 *    (RESTRICT no longer makes sense once NULLs are allowed).
 *  - event_type VARCHAR(30) NOT NULL DEFAULT 'email' discriminates the rows.
 *    Values used in this iteration: 'email', 'payment'.
 *
 * The CI4-generated FK name is resolved dynamically from
 * information_schema so a differently named constraint on the VPS does not
 * break the deploy.
 */
class AlterReservationEmailHistoryForSystemEvents extends Migration
{
    private const TABLE = 'reservation_email_history';

    public function up()
    {
        // 1. Drop the existing FK on template_id (name generated by CI4).
        $fkName = $this->resolveTemplateForeignKeyName();
        if ($fkName !== null) {
            $this->db->query('ALTER TABLE `' . self::TABLE . '` DROP FOREIGN KEY `' . $fkName . '`');
        }

        // 2. template_id -> NULLABLE.
        $this->db->query('ALTER TABLE `' . self::TABLE . '` MODIFY `template_id` CHAR(36) NULL');

        // 3. Add event_type discriminator + index.
        if (! $this->db->fieldExists('event_type', self::TABLE)) {
            $this->db->query(
                'ALTER TABLE `' . self::TABLE . "` ADD COLUMN `event_type` VARCHAR(30) NOT NULL DEFAULT 'email' AFTER `template_name`"
            );
            $this->db->query(
                'ALTER TABLE `' . self::TABLE . '` ADD INDEX `reservation_email_history_event_type` (`event_type`)'
            );
        }

        // 4. Re-add the FK, now tolerant of NULLs.
        $this->db->query(
            'ALTER TABLE `' . self::TABLE . '` '
            . 'ADD CONSTRAINT `reservation_email_history_template_id_foreign` '
            . 'FOREIGN KEY (`template_id`) REFERENCES `email_templates` (`id`) '
            . 'ON DELETE SET NULL ON UPDATE RESTRICT'
        );
    }

    public function down()
    {
        // 1. Drop the (re-added) FK on template_id.
        $fkName = $this->resolveTemplateForeignKeyName();
        if ($fkName !== null) {
            $this->db->query('ALTER TABLE `' . self::TABLE . '` DROP FOREIGN KEY `' . $fkName . '`');
        }

        // 2. Drop the event_type index + column.
        if ($this->db->fieldExists('event_type', self::TABLE)) {
            $this->db->query('ALTER TABLE `' . self::TABLE . '` DROP INDEX `reservation_email_history_event_type`');
            $this->db->query('ALTER TABLE `' . self::TABLE . '` DROP COLUMN `event_type`');
        }

        // 3. Remove rows that could not exist under the old schema (system
        //    events have no template_id) so the NOT NULL restore cannot fail.
        $this->db->query('DELETE FROM `' . self::TABLE . '` WHERE `template_id` IS NULL');

        // 4. template_id -> NOT NULL again.
        $this->db->query('ALTER TABLE `' . self::TABLE . '` MODIFY `template_id` CHAR(36) NOT NULL');

        // 5. Re-add the original RESTRICT/RESTRICT FK.
        $this->db->query(
            'ALTER TABLE `' . self::TABLE . '` '
            . 'ADD CONSTRAINT `reservation_email_history_template_id_foreign` '
            . 'FOREIGN KEY (`template_id`) REFERENCES `email_templates` (`id`) '
            . 'ON DELETE RESTRICT ON UPDATE RESTRICT'
        );
    }

    /**
     * Resolve the current FK constraint name on
     * reservation_email_history.template_id, whatever CI4 called it.
     */
    private function resolveTemplateForeignKeyName(): ?string
    {
        $sql = 'SELECT CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = ?
                  AND TABLE_NAME = ?
                  AND COLUMN_NAME = ?
                  AND REFERENCED_TABLE_NAME IS NOT NULL
                LIMIT 1';

        $row = $this->db->query($sql, [
            $this->db->getDatabase(),
            self::TABLE,
            'template_id',
        ])->getRow();

        return $row->CONSTRAINT_NAME ?? null;
    }
}
