<template>
  <div class="row justify-content-center">
    <div class="col-6">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Costo unitario</th>
            <th>cantidad</th>
            <th>total</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <1>saasasas</1>
                </td>
                <td>
                    <2>saasasas</2>
                </td>
                <td>
                    <3>saasasas</3>
                </td>
                <td>
                    <4>saasasas</4>
                </td>
            </tr>
            <tr>
                <td>
                    <1>saasasas</1>
                </td>
                <td>
                    <2>saasasas</2>
                </td>
                <td>
                    <3>saasasas</3>
                </td>
                <td>
                    <4>saasasas</4>
                </td>
            </tr>
            <tr>
                <td>
                    <1>saasasas</1>
                </td>
                <td>
                    <2>saasasas</2>
                </td>
                <td>
                    <3>saasasas</3>
                </td>
                <td>
                    <4>saasasas</4>
                </td>
            </tr>
            <tr>
                <td>
                    <1>saasasas</1>
                </td>
                <td>
                    <2>saasasas</2>
                </td>
                <td>
                    <3>saasasas</3>
                </td>
                <td>
                    <4>saasasas</4>
                </td>
            </tr>
            <tr>
                <td>
                    <1>saasasas</1>
                </td>
                <td>
                    <2>saasasas</2>
                </td>
                <td>
                    <3>saasasas</3>
                </td>
                <td>
                    <4>saasasas</4>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3">TOTAL</th>
                <th>$0</th>
            </tr>
        </tfoot>
      </table>
    </div>
  </div>
</template>
<script setup></script>
