<?php

namespace App\Repositories;

use App\Models\CustomPaymentLinkModel;

/**
 * B5 — persistence for custom_payment_links.
 *
 * Double whitelist: create()/updateEditable() only accept the fields an admin
 * may set from a request. Stripe identifiers, status and paid_at are written
 * exclusively by the service through attachSession()/markPaid()/updateStatus().
 */
class CustomPaymentLinkRepository
{
    /**
     * Fields an authenticated admin is allowed to provide when creating a link.
     * `status`, `paid_at` and every `stripe_*` column are deliberately absent:
     * they are written only by the service through the dedicated mutators.
     */
    private const CREATE_WHITELIST = [
        'reservation_id',
        'customer_name',
        'customer_email',
        'description',
        'amount',
        'currency',
        'created_by',
    ];

    protected $model;

    public function db()
    {
        return \Config\Database::connect();
    }

    public function __construct()
    {
        $this->model = new CustomPaymentLinkModel();
    }

    /**
     * @return object[] Newest first.
     */
    public function getAll(): array
    {
        return $this->model->orderBy('created_at', 'DESC')->findAll();
    }

    public function findById(string $id): ?object
    {
        return $this->model->find($id);
    }

    /**
     * B6 — the newest still-collectable link for a reservation, if any.
     * "Collectable" means status 'pending' (a Stripe session exists and has not
     * been paid or cancelled). Used to block a second balance link for the same
     * reservation (double-charge guard).
     */
    public function findPendingByReservation(string $reservationId): ?object
    {
        return $this->model
            ->where('reservation_id', $reservationId)
            ->where('status', 'pending')
            ->orderBy('created_at', 'DESC')
            ->first();
    }

    /** @return object[] */
    public function getByReservation(string $reservationId): array
    {
        return $this->model
            ->where('reservation_id', $reservationId)
            ->orderBy('created_at', 'DESC')
            ->findAll();
    }

    /** @return array<string, float> Paid personalized amounts keyed by reservation id. */
    public function paidTotalsByReservation(array $reservationIds): array
    {
        if ($reservationIds === []) {
            return [];
        }

        $rows = $this->db()->table('custom_payment_links')
            ->select('reservation_id, SUM(amount) AS paid_amount')
            ->whereIn('reservation_id', $reservationIds)
            ->where('status', 'paid')
            ->groupBy('reservation_id')
            ->get()
            ->getResultArray();

        $totals = [];
        foreach ($rows as $row) {
            $totals[(string) $row['reservation_id']] = round((float) $row['paid_amount'], 2);
        }

        return $totals;
    }

    /**
     * Create a link from admin-supplied data. Only CREATE_WHITELIST keys are
     * persisted; status defaults to 'pending' at the DB level. The id is
     * pre-generated by the service so it can travel in the Stripe metadata
     * before the row exists.
     *
     * @return string The new link id.
     */
    public function create(array $data, string $id): string
    {
        $clean       = array_intersect_key($data, array_flip(self::CREATE_WHITELIST));
        $clean['id'] = $id;

        $this->model->insert($clean);

        return $id;
    }

    /**
     * Persist the Stripe session created for a pending link. Service-only.
     */
    public function attachSession(string $id, string $sessionId, string $paymentUrl, ?string $expiresAt): bool
    {
        return (bool) $this->model->update($id, [
            'stripe_session_id' => $sessionId,
            'payment_url'       => $paymentUrl,
            'expires_at'        => $expiresAt,
            'status'            => 'pending',
        ]);
    }

    /**
     * Mark a link as paid. Service-only, idempotent at the caller.
     */
    public function markPaid(string $id, string $paymentIntentId, string $paidAt): bool
    {
        // Conditional update is the idempotency gate for webhook + verify-payment.
        // Model::update() can report true even when no row changed, so use affectedRows.
        $this->db()->table('custom_payment_links')
            ->where('id', $id)
            ->where('status', 'pending')
            ->update([
            'status'                   => 'paid',
            'stripe_payment_intent_id' => $paymentIntentId,
            'paid_at'                  => $paidAt,
        ]);

        return $this->db()->affectedRows() === 1;
    }

    /**
     * Change the status (e.g. 'cancelled'). Service-only.
     */
    public function updateStatus(string $id, string $status): bool
    {
        return (bool) $this->model->update($id, ['status' => $status]);
    }

    public function delete(string $id): bool
    {
        return (bool) $this->model->delete($id);
    }
}
